name: build.v1.golang
on:
  workflow_call:
    inputs:
      APP_NAME:
        description: 'This app name'
        required: true
        type: string
      APP_DOCKER_REPOSITORIES:
        description: 'Docker repositories name'
        required: true
        type: string
      GCP_PROJECT:
        description: 'GCP project'
        required: true
        type: string
      ZMODE:
        description: "Mode name [dev, prod, ...]"
        required: false
        type: string
        default: dev
      GO_VERSION:
        description: 'Vseion 棄用 哪次不棄用'
        required: false
        type: string
        default: "1.20"
      GO_BUILD_PATH:
        description: 'main.go path'
        required: false
        type: string
        default: "./cmd/server/"
      SERVER_NAME:
        description: 'server name in dockerfile'
        required: false
        type: string
        default: "server"
      GH_TOKEN:
        description: 'GH_APP_CREDENTIALS_TOKEN'
        required: false
        type: string
        default: ${{ secrets.GH_APP_CREDENTIALS_TOKEN }}
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ⚙️ Obtain GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN=$(npx obtain-github-app-installation-access-token ci ${{ inputs.GH_TOKEN }})
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"
      - name: ⚙️ Setting GitHub Auth
        run : |
           git config --global url."https://oauth2:$GITHUB_TOKEN@github.com/lctech-tw".insteadOf "https://github.com/lctech-tw" 
        env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
      - name: ⚙️ Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json:  ${{ secrets.GCP_SA_KEY_GITHUB_CI }}
      - name: ⚙️ Initialize Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: ⚙️ setting docker auth
        run: |
          gcloud auth configure-docker -q
          gcloud auth configure-docker $(echo ${{ inputs.APP_DOCKER_REPOSITORIES }}  | cut -d "/" -f 1) -q
      - name: ⚙️ Set up Golang
        uses: actions/setup-go@v4
        with:
          ## use the version of Go in go.mod
          # go-version: ${{ inputs.GO_VERSION }}
          ## use go.mod version
          go-version-file: './go.mod'
      - name: ⚙️ Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: ⚙️ Build Golang
        run: |
          cd ${{ inputs.GO_BUILD_PATH }} && go build .
      - name: ⚙️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: ⛴ Docker build / tag / push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          cache-to: type=gha,mode=max
          cache-from: type=gha
          file: .github/docker/Dockerfile
          tags: |
            ${{ inputs.APP_DOCKER_REPOSITORIES }}/${{ inputs.APP_NAME }}:${{ github.sha }}
            ${{ inputs.APP_DOCKER_REPOSITORIES }}/${{ inputs.APP_NAME }}:${{ inputs.ZMODE }}-latest
            ${{ inputs.APP_DOCKER_REPOSITORIES }}/${{ inputs.APP_NAME }}:${{ inputs.ZMODE }}-${{ github.run_number }}
            ${{ inputs.APP_DOCKER_REPOSITORIES }}/${{ inputs.APP_NAME }}:${{ github.ref_name }}-${{ github.run_number }}
          build-args: |
            SERVER_NAME=${{ inputs.SERVER_NAME }}
        
        ## Use docker buildx cmd
        # run : |
        #   docker buildx build \
        #     --cache-from=type=gha \
        #     --cache-to=type=gha,mode=max \
        #     -f .github/docker/Dockerfile \
        #     -t ${{ inputs.APP_DOCKER_REPOSITORIES }}/${{ inputs.APP_NAME }} \
        #     -t ${{ inputs.APP_DOCKER_REPOSITORIES }}/${{ inputs.APP_NAME }} ${{ inputs.APP_DOCKER_REPOSITORIES }}/${{ inputs.APP_NAME }}:${GITHUB_SHA::7} \
        #     -t ${{ inputs.APP_DOCKER_REPOSITORIES }}/${{ inputs.APP_NAME }} ${{ inputs.APP_DOCKER_REPOSITORIES }}/${{ inputs.APP_NAME }}:${{ github.run_number }} \
        #     -t ${{ inputs.APP_DOCKER_REPOSITORIES }}/${{ inputs.APP_NAME }} ${{ inputs.APP_DOCKER_REPOSITORIES }}/${{ inputs.APP_NAME }}:${{ inputs.ZMODE }}-${{ github.run_number }} \
        #     .
