name: v1.notify
on:
  workflow_call:
    inputs:
      CI_STATUS:
        description: 'status'
        required: true
        type: string
      GROUP:
        description: 'slack group'
        required: true
        type: string
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json:  ${{ secrets.GCP_SA_KEY_GITHUB_CI }}
      - name: ⚙️ Initialize Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: 📨 Notification via Slack
        if: always()
        run: |
          curl -LJO https://raw.githubusercontent.com/lctech-tw/util_scripts/main/notify_slack.sh 
          if [[ '${{ inputs.CI_STATUS }}' == 'success' ]] ;then
            echo "Run slack on Success (O)"
            bash ./notify_slack.sh -s -g=${{ inputs.GROUP }}
          else
            echo "Run slack on Fail (X)"
            bash ./notify_slack.sh -f -g=${{ inputs.GROUP }}
          fi
