name: Test

on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        required: false
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello ${{ inputs.username }}"